import unicodedata
from googletrans import Translator

# English response dictionary
RESPONSES_EN = {
    "fever": "Rest well, drink plenty of water or oral rehydration fluids, and consult a doctor if fever is high or lasts more than a few days.",
  "cough": "Try honey with warm water or ginger tea to soothe the throat, and consult a doctor if cough is severe or persistent.",
  "cold": "Rest properly, drink warm fluids like soup or herbal tea, and consider saline nasal spray for congestion.",
  "headache": "Rest in a quiet place, avoid bright lights, stay hydrated, and see a doctor if pain is severe or frequent.",
  "migraine": "Rest in a dark, quiet room, use a cold compress on the forehead, and seek medical care if attacks are frequent.",
  "sinusitis": "Steam inhalation and warm fluids may help relieve pressure; consult a doctor if facial pain or fever occurs.",
  "sore_throat": "Gargle with warm salt water and drink warm fluids like tea or soup; see a doctor if swallowing is painful.",
  "flu": "Get enough rest, drink fluids regularly, and consult a doctor if weakness or fever worsens.",
  "asthma": "Avoid smoke and allergens, use inhalers as prescribed, and seek medical help if breathing becomes difficult.",
  "allergy": "Avoid known triggers, keep surroundings clean, and consult a doctor if symptoms worsen.",
  "bronchitis": "Rest well, drink warm fluids, avoid smoke, and follow doctor-recommended treatment if symptoms persist.",
  "pneumonia": "Seek medical care promptly, rest adequately, and follow professional treatment guidance.",
  "stomach_ache": "Eat light foods, drink water, and consult a doctor if pain is severe or persistent.",
  "indigestion": "Eat smaller meals, avoid spicy food, and drink warm water; see a doctor if discomfort continues.",
  "acidity": "Avoid oily or spicy foods, drink warm water, and consult a doctor if symptoms are frequent.",
  "diarrhea": "Prevent dehydration by drinking oral rehydration solution and water, and avoid greasy foods.",
  "constipation": "Increase fiber intake, drink plenty of water, and stay physically active.",
  "vomiting": "Take small sips of water or ORS and seek medical care if vomiting continues.",
  "nausea": "Rest, avoid strong smells, and sip ginger tea or warm water.",
  "food_poisoning": "Rest, drink ORS and water, and consult a doctor if fever or blood in stool appears.",
  "diabetes": "Monitor blood sugar regularly, follow a healthy diet, and follow your doctor’s instructions.",
  "hypertension": "Reduce salt intake, exercise regularly, manage stress, and follow medical advice.",
  "low_blood_pressure": "Drink fluids, rise slowly from sitting, and consult a doctor if dizziness occurs.",
  "chest_pain": "Rest immediately and seek urgent medical care, especially if pain is severe or spreading.",
  "back_pain": "Rest the back, maintain good posture, apply heat if helpful, and consult a doctor if pain persists.",
  "neck_pain": "Avoid strain, do gentle stretches, and use a warm compress if needed.",
  "joint_pain": "Rest affected joints, do gentle movement, and consult a doctor if swelling occurs.",
  "arthritis": "Keep joints active with gentle exercise and follow medical guidance for pain management.",
  "muscle_pain": "Rest the muscle, apply warm compress, and hydrate well.",
  "leg_cramps": "Stretch gently and drink enough water throughout the day.",
  "fatigue": "Ensure adequate sleep, eat balanced meals, and stay hydrated.",
  "dehydration": "Drink water, oral rehydration solution, or coconut water and seek care if symptoms worsen.",
  "dizziness": "Sit or lie down safely, drink fluids, and consult a doctor if fainting occurs.",
  "anxiety": "Practice deep breathing and relaxation techniques, and seek professional help if anxiety interferes with daily life.",
  "depression": "Seek mental health support, talk to a trusted person, and consult a professional for proper care.",
  "stress": "Take breaks, practice relaxation techniques, and maintain a balanced routine.",
  "insomnia": "Maintain a regular sleep schedule, reduce screen time at night, and seek help if sleeplessness continues.",
  "skin_rash": "Keep the area clean and dry, avoid irritants, and consult a doctor if rash spreads.",
  "itching": "Avoid scratching, apply soothing lotion, and seek care if itching is severe.",
  "fungal_infection": "Keep the area dry and clean, and consult a doctor if infection spreads.",
  "ear_pain": "Avoid water entry into the ear and consult a doctor if pain or discharge occurs.",
  "eye_strain": "Rest your eyes, reduce screen time, and use proper lighting.",

  "eye_fatigue": "Rest eyes regularly, reduce screen exposure, and use proper lighting.",
  "ear_blockage": "Avoid inserting objects into the ear, try swallowing or yawning, and consult a doctor if hearing loss occurs.",
  "toothache": "Rinse the mouth with warm salt water, avoid hard foods, and see a dentist if pain persists.",
  "mouth_ulcer": "Avoid spicy foods, rinse with salt water, and consult a doctor if ulcers last more than two weeks.",
  "bad_breath": "Maintain oral hygiene, drink water frequently, and consult a dentist if the problem continues.",
  "dry_mouth": "Sip water often and consult a doctor if dryness is persistent.",
  "bleeding_gums": "Brush gently, floss carefully, and see a dentist if bleeding is frequent.",
  "acne": "Clean skin gently, avoid squeezing pimples, and consult a doctor if acne is severe.",
  "boils": "Keep the area clean and dry, and consult a doctor if fever or pain increases.",
  "dry_skin": "Use moisturizer regularly, avoid hot showers, and drink enough water.",
  "dandruff": "Wash hair regularly with mild shampoo and consult a doctor if scalp irritation occurs.",
  "hair_fall": "Reduce stress, eat nutritious food, and consult a doctor if hair loss is sudden.",
  "urinary_burning": "Drink plenty of water and consult a doctor if pain or fever develops.",
  "menstrual_cramps": "Rest, apply a warm heating pad, and consult a doctor if pain is severe.",
  "night_sweats": "Keep the room cool and consult a doctor if sweating is frequent.",
  "palpitations": "Sit calmly, breathe slowly, and seek urgent care if chest pain occurs.",
  "cold_hands": "Warm hands gradually and consult a doctor if color changes occur.",
  "cold_feet": "Keep feet warm and seek medical advice if numbness develops.",
  "muscle_soreness": "Rest the muscles, hydrate well, and use gentle stretching.",
  "sun_fatigue": "Move to a cool place, rest, and drink water or oral rehydration fluids.",
  "travel_fatigue": "Get adequate rest, hydrate well, and eat light meals.",
  "jet_lag": "Adjust sleep schedule gradually and get natural sunlight during the day.",
  "memory_lapse": "Rest well, reduce stress, and consult a doctor if confusion increases.",
  "concentration_difficulty": "Take short breaks, stay hydrated, and ensure proper sleep.",
  "mental_exhaustion": "Reduce workload, rest adequately, and seek professional help if burnout persists.",
  "mood_swings": "Maintain a regular routine and consult a professional if mood changes are severe.",
  "panic_symptoms": "Sit calmly, focus on slow breathing, and seek urgent care if chest pain occurs.",
  "general_discomfort": "Rest, hydrate, and consult a doctor if symptoms worsen."
}

# Multilingual input keywords mapped to English keys
INPUT_KEYWORDS = {
    'hi': {
        "बुखार": "fever",
        "फ़ीवर": "fever",
        "खांसी": "cough",
        "कफ़": "cough",
        "जुकाम": "cold",
        "सर्दी": "cold",
        "सिरदर्द": "headache",
        "मधुमेह": "diabetes",
        "शुगर": "diabetes",
        "उच्च रक्तचाप": "hypertension",
        "ब्लड प्रेशर": "hypertension",
        "दमा": "asthma",
        "एलर्जी": "allergy",
        "फ्लू": "flu",
        "पेट दर्द": "stomach ache",
        "दस्त": "diarrhea",
        "पीठ दर्द": "back pain",
        "अवसाद": "depression",
        "चिंता": "anxiety",
        "गठिया": "arthritis",
        "सलसिल": "bronchitis",
        "एनीमिया": "anemia",
        "मूत्र मार्ग संक्रमण": "urinary tract infection",
        "कान का संक्रमण": "ear infection",
        "साइनस": "sinusitis",
        "खुजली": "skin rash",
        "एक्जिमा": "eczema",
        "सोरायसिस": "psoriasis",
        "गैस्ट्रोएंटेराइटिस": "gastroenteritis",
        "कब्ज़": "constipation",
        "अनिद्रा": "insomnia",
        "माइग्रेन": "migraine",
        "मोटापा": "obesity",
        "थायरॉयड": "thyroid disorder",
        "कोलेस्ट्रॉल": "cholesterol",
        "ऑस्टियोपोरोसिस": "osteoporosis",
        "स्ट्रोक": "stroke",
        "कैंसर": "cancer",
        "टीबी": "tuberculosis",
        "हेपेटाइटिस": "hepatitis",
        "एड्स": "HIV/AIDS",
        "मलेरिया": "malaria",
        "चिकनगुनिया": "chickenpox",
        "खसरा": "measles",
        "डेंगू": "dengue",
        "ज़िका वायरस": "zika virus",
        "पोलियो": "polio",
        "कुत्ते का काटना": "rabies",
        "टाइफाइड": "typhoid",
        "हैजिया": "cholera",
        "अस्पताल": "hospital",
        "डॉक्टर": "doctor",
    },
    'mr': {
        "ताप": "fever",
        "खोकला": "cough",
        "सर्दी": "cold",
        "मायग्रेन": "headache",
        "मधुमेह": "diabetes",
        "उच्च रक्तदाब": "hypertension",
        "दमा": "asthma",
        "अॅलर्जी": "allergy",
        "फ्लू": "flu",
        "पोटदुखी": "stomach ache",
        "जुलाब": "diarrhea",
        "मागदुखी": "back pain",
        "निराशा": "depression",
        "तणाव": "anxiety",
        "आपटी": "arthritis",
        "ब्रॉन्कायटीस": "bronchitis",
        "अॅनीमिया": "anemia",
        "मूत्रमार्गाचा संसर्ग": "urinary tract infection",
        "कर्णदाह": "ear infection",
        "साइनसिटिस": "sinusitis",
        "त्वचेवरचा डाग": "skin rash",
        "एक्झिमा": "eczema",
        "सोरायसिस": "psoriasis",
        "गॅस्ट्रोएंटराइटिस": "gastroenteritis",
        "कब्ज": "constipation",
        "निद्रा नाही": "insomnia",
        "मायग्रेन": "migraine",
        "लठ्ठपणा": "obesity",
        "थायरॉईड": "thyroid disorder",
        "कोलेस्ट्रॉल": "cholesterol",
        "ऑस्टिओपोरोसिस": "osteoporosis",
        "स्ट्रोक": "stroke",
        "कॅन्सर": "cancer",
        "क्षयरोग": "tuberculosis",
        "हेपाटायटिस": "hepatitis",
        "एचआयव्ही/एड्स": "HIV/AIDS",
        "मलेरिया": "malaria",
        "चिकनपॉक्स": "chickenpox",
        "खसरा": "measles",
        "डेंग्यू": "dengue",
        "झिका व्हायरस": "zika virus",
        "पोलिओ": "polio",
        "रॅबीज": "rabies",
        "टायफॉईड": "typhoid",
        "कोलेरा": "cholera",
        "रुग्णालय": "hospital",
        "डॉक्टर": "doctor",
    },
    'ta': {
        "காய்ச்சல்": "fever",
        "படர்ப்பு": "cough",
        "காய்ச்சல் மற்றும் போது குளிர்ச்சி": "cold",
        "தலைவலி": "headache",
        "பருமன் நீர் சர்க்கரை": "diabetes",
        "உயர் இரத்த அழுத்தம்": "hypertension",
        "அஸ்துமா": "asthma",
        "அலெர்ஜி": "allergy",
        "பொதி": "flu",
        "குடல் வலி": "stomach ache",
        "திண்டாட்டம்": "diarrhea",
        "பின்புற வலி": "back pain",
        "உதடுபாதம்": "depression",
        "கவலை": "anxiety",
        "உடலிழப்பு": "arthritis",
        "நுரையீரல் வியாதி": "bronchitis",
        "இரத்த சிவப்பு குறைவு": "anemia",
        "மூத்திர பாதை தொற்று": "urinary tract infection",
        "காது தொற்று": "ear infection",
        "சைனஸ்": "sinusitis",
        "தோல் உதிர்வு": "skin rash",
        "எக்ஸிமா": "eczema",
        "பசுமை ஓராட்டிகள்": "psoriasis",
        "குடல் அழற்சித்தன்மை": "gastroenteritis",
        "கட்டித்தல்": "constipation",
        "உறக்கம் குறைவு": "insomnia",
        "மயக்கக்கோளாறு": "migraine",
        "ஊட்டச்சத்து குறைவு": "obesity",
        "தையிராய்டு நோய்": "thyroid disorder",
        "கொலஸ்டெரால்": "cholesterol",
        "எலும்பு சிதைவு": "osteoporosis",
        "மூளைப்பிடிப்பு": "stroke",
        "புற்றுநோய்": "cancer",
        "நோய் காசநோய்": "tuberculosis",
        "கடும் கல்லீரல் அழற்சி": "hepatitis",
        "எச்சரிக்கை": "HIV/AIDS",
        "கண்டிப்பான கிருமிநாசினி": "malaria",
        "கிளிக்கன் பாக்ஸ்": "chickenpox",
        "காசநோய்": "measles",
        "டெங்கு": "dengue",
        "ஜிகா வைரஸ்": "zika virus",
        "பாலியோ": "polio",
        "குப்பை நோய்": "rabies",
        "டைபாய்டு": "typhoid",
        "காலரா": "cholera",
        "மருத்துவமனை": "hospital",
        "ஆறுமுறை நிபுணர்": "doctor",
    },
    'bn': {
        "জ্বর": "fever",
        "কাশি": "cough",
        "ঠান্ডা": "cold",
        "মাথাব্যাথা": "headache",
        "ডায়াবেটিস": "diabetes",
        "উচ্চ রক্তচাপ": "hypertension",
        "অ্যাজমা": "asthma",
        "অ্যালার্জি": "allergy",
        "ফ্লু": "flu",
        "পেট ব্যথা": "stomach ache",
        "হাঁপানি": "diarrhea",
        "পিঠের ব্যথা": "back pain",
        "মনোসংকট": "depression",
        "উদ্বেগ": "anxiety",
        "অর্থ্রাইটিস": "arthritis",
        "ব্রঙ্কাইটিস": "bronchitis",
        "রক্তস্বল্পতা": "anemia",
        "মূত্রনালী সংক্রমণ": "urinary tract infection",
        "কানের ইনফেকশন": "ear infection",
        "সাইনুসাইটিস": "sinusitis",
        "চামড়ার র‍্যাশ": "skin rash",
        "এক্সিমা": "eczema",
        "সোরায়াসিস": "psoriasis",
        "গ্যাস্ট্রোএনটেরাইটিস": "gastroenteritis",
        "কব্জ": "constipation",
        "অনিদ্রা": "insomnia",
        "মাইগ্রেন": "migraine",
        "স্থূলতা": "obesity",
        "থাইরয়েড ডিজিজ": "thyroid disorder",
        "কোলেস্টেরল": "cholesterol",
        "অস্টিওপরোসিস": "osteoporosis",
        "স্ট্রোক": "stroke",
        "ক্যান্সার": "cancer",
        "ক্ষয়রোগ": "tuberculosis",
        "হেপাটাইটিস": "hepatitis",
        "এইচআইভি/এইডস": "HIV/AIDS",
        "ম্যালেরিয়া": "malaria",
        "চিকেনপক্স": "chickenpox",
        "হামসা": "measles",
        "ডেঙ্গু": "dengue",
        "জিকা ভাইরাস": "zika virus",
        "পোলিও": "polio",
        "কুকুর কামড়": "rabies",
        "টাইফয়েড": "typhoid",
        "কলেরা": "cholera",
        "হাসপাতাল": "hospital",
        "ডাক্তার": "doctor",
    },
    'te': {
        "జ్వరం": "fever",
        "చప్పుడు": "cough",
        "జలుబు": "cold",
        " తలనొప్పి": "headache",
        "మధుమేహం": "diabetes",
        "ఉన్నత రక్తపోటు": "hypertension",
        "దమ": "asthma",
        "అలర్జీ": "allergy",
        "ఫ్లూ": "flu",
        "వాంతులు": "stomach ache",
        "డయరియా": "diarrhea",
        "పైను నొప్పి": "back pain",
        "మనస్తాపం": "depression",
        "ఆందోళన": "anxiety",
        "ఆర్థరైటిస్": "arthritis",
        "బ్రాంకటైటిస్": "bronchitis",
        "అనిమియా": "anemia",
        "మూత్రాశయ ఇన్ఫెక్షన్": "urinary tract infection",
        "చెవి ఇన్ఫెక్షన్": "ear infection",
        "సైనసైటిస్": "sinusitis",
        "చర్మ ర్యాష్": "skin rash",
        "ఎగ్జిమా": "eczema",
        "సోరాయసిస్": "psoriasis",
        "గ్యాస్ట్రోఎంటరైటిస్": "gastroenteritis",
        "కబ్జితనం": "constipation",
        "నిద్రలేమి": "insomnia",
        "మైగ్రైన్": "migraine",
        "స్థూలత్వం": "obesity",
        "తోయిరాయిడ్": "thyroid disorder",
        "కోలెస్ట్రాల్": "cholesterol",
        "అస్థిముల్నశం": "osteoporosis",
        "స్ట్రోక్": "stroke",
        "కేన్సర్": "cancer",
        "క్షయ రోగం": "tuberculosis",
        "హెపటైటిస్": "hepatitis",
        "హెచ్ ఐ వి/ఏ ఆ ద్స్": "HIV/AIDS",
        "మలేరియా": "malaria",
        "చికెన్ పాక్స్": "chickenpox",
        "మీసల్స్": "measles",
        "డెన్గ్యూ": "dengue",
        "జికా వైరస్": "zika virus",
        "పోలియో": "polio",
        "ఖాళీ కుక్క గొసుక": "rabies",
        "టైఫాయిడ్": "typhoid",
        "కాలరా": "cholera",
        "హాస్పిటల్": "hospital",
        "డాక్టర్": "doctor",
    },
    'kn': {
        "ಜ್ವರ": "fever",
        "ತಸು": "cough",
        "ಜರಳು": "cold",
        "ತಲೆಯನೋವು": "headache",
        "ಮಧುಮೇಹ": "diabetes",
        "ಹೈಪರ್ಟೆನ್ಷನ್": "hypertension",
        "ಅಸ್ಥಮಾ": "asthma",
        "ಅಲರ್ಜಿ": "allergy",
        "ಕೀಲು": "flu",
        "ಒಳು": "stomach ache",
        "ಅರೆ": "diarrhea",
        "ಕೋಪನೆಯ ನೋವು": "back pain",
        "ಅವಸಾದ": "depression",
        "ಉದ್ವೇಗ": "anxiety",
        "ಸಂಧಿ ನೋವು": "arthritis",
        "ಬ್ರಾಂಕೈಟಿಸ್": "bronchitis",
        "ಅನಿಮಿಯಾ": "anemia",
        "ಮೂತ್ರದ ಮಾರ್ಗದ ಸೋಂಕು": "urinary tract infection",
        "ಕಿವಿ ಸೋಂಕು": "ear infection",
        "ಸೈನಸೈಟಿಸ್": "sinusitis",
        "ತಳೆಯ ಮೇಲಿನ ಚರ್ಮ": "skin rash",
        "ಎಕ್ಜೀಮಾ": "eczema",
        "ಸೋರಾಯಾಸಿಸ್": "psoriasis",
        "ಗ್ಯಾಸ್ಟ್ರೋಎಂಟರೈಟಿಸ್": "gastroenteritis",
        "ಕೊಬ್ಬು": "constipation",
        "ನಿದ್ರೆ ವ್ಯತ್ಯಯ": "insomnia",
        "ಮೈಗ್ರೇನ್": "migraine",
        "ಸ್ಥೂಲತೆ": "obesity",
        "ಥೈರಾಯ್ಡ್": "thyroid disorder",
        "ಕೊಲೆಸ್ಟೆರಾಲ್": "cholesterol",
        "ಅಸ್ಥಿಮೊರೋಸಿಸ್": "osteoporosis",
        "ಸ್ಟ್ರೋಕ್": "stroke",
        "ಕ್ಯಾನ್ಸರ್": "cancer",
        "ಕ್ಷಯ": "tuberculosis",
        "ಹೆಪಟೈಟಿಸ್": "hepatitis",
        "ಎಚ್. ಐ. ವಿ/ಎಡ್ಸ್": "HIV/AIDS",
        "ಮಲೇರಿಯಾ": "malaria",
        "ಚಿಕನ್ ಪಾಕ್ಸ್": "chickenpox",
        "ಮೀಸಲ್ಸ್": "measles",
        "ಡೆಂಗ್ಯೂ": "dengue",
        "ಜಿಕಾ ವೈರಸ್": "zika virus",
        "ಪೋಲಿಯೋ": "polio",
        "ರೇಬೀಸ್": "rabies",
        "ಟೈಫಾಯ್ಡ್": "typhoid",
        "ಕೊಲೆರಾ": "cholera",
        "ಆಸ್ಪತ್ರೆ": "hospital",
        "ಡಾಕ್ಟರ್": "doctor",
    },
    'gu': {
        "બુખાર": "fever",
        "ખાંસી": "cough",
        "ઠંડી": "cold",
        "શેરીમાં દુખાવો": "headache",
        "ડાયાબિટીસ": "diabetes",
        "ઉચ્ચ રક્તચાપ": "hypertension",
        "અસ્થમા": "asthma",
        "એલર્જી": "allergy",
        "ફ્લુ": "flu",
        "પેટ દુખાવો": "stomach ache",
        "ડાયરિયા": "diarrhea",
        "પીઠ દુખાવો": "back pain",
        "આત્મઘાત": "depression",
        "ઉદાસી": "anxiety",
        "જોયન્ટમાં દુખાવો": "arthritis",
        "બ્રોંકાઈટીસ": "bronchitis",
        "અનિમિયા": "anemia",
        "મૂત્ર માર્ગ સંક્રમણ": "urinary tract infection",
        "કાનનો ઈન્ફેક્શન": "ear infection",
        "સાઇનસાઇટિસ": "sinusitis",
        "ચામડીની ઉમેરી": "skin rash",
        "એક્સીમા": "eczema",
        "સોરાયસિસ": "psoriasis",
        "ગૅસ્ટ્રોએન્ટરાઇટિસ": "gastroenteritis",
        "કબજ": "constipation",
        "નિદાન": "insomnia",
        "માઈગ્રેન": "migraine",
        "મોટાપો": "obesity",
        "થાઇરોઇડ બિમારી": "thyroid disorder",
        "કોલેસ્ટ્રોલ": "cholesterol",
        "ઓસ્ટિઓપોરોસિસ": "osteoporosis",
        "સ્ટ્રોક": "stroke",
        "કૅન્સર": "cancer",
        "ટ્યુબરક્યુલોસિસ": "tuberculosis",
        "હેપેટાઈટિસ": "hepatitis",
        "એચઆઈવી/એડ્સ": "HIV/AIDS",
        "મેલેરિયા": "malaria",
        "ચિકનપોક્સ": "chickenpox",
        "ખસરો": "measles",
        "ડેન્ગ્યુ": "dengue",
        "ઝિકા વાયરસ": "zika virus",
        "પોલિયો": "polio",
        "રેવિઝ": "rabies",
        "ટાઇફોયડ": "typhoid",
        "કોલેરા": "cholera",
        "હૉસ્પિટલ": "hospital",
        "ડૉક્ટર": "doctor",
    },
    'pa': {
        "ਬੁਖਾਰ": "fever",
        "ਖਾਂਸੀ": "cough",
        "ਸਰਦੀ": "cold",
        "ਸਿਰਦਰਦ": "headache",
        "ਮਧੁਮੇਹ": "diabetes",
        "ਉੱਚ ਰਕਤਚਾਪ": "hypertension",
        "ਦਮਾ": "asthma",
        "ਅਲਰਜੀ": "allergy",
        "ਫਲੂ": "flu",
        "ਪੀਟ ਦਰਦ": "stomach ache",
        "ਦਸਤ": "diarrhea",
        "ਪੀਠ ਦਰਦ": "back pain",
        "ਡਿਪ੍ਰੈਸ਼ਨ": "depression",
        "ਚਿੰਤਾ": "anxiety",
        "ਗਠਿਆ": "arthritis",
        "ਬ੍ਰੋਂਕਾਈਟਿਸ": "bronchitis",
        "ਐਨੀਮੀਆ": "anemia",
        "ਮੂਤਰ ਰਾਹ ਇੰਫੈਕਸ਼ਨ": "urinary tract infection",
        "ਕਾਨ ਦਾ ਇੰਫੈਕਸ਼ਨ": "ear infection",
        "ਸਾਈਨਸਾਈਟਿਸ": "sinusitis",
        "ਚਮੜੀ ਰੈਸ਼": "skin rash",
        "ਐਕਜ਼ੀਮਾ": "eczema",
        "ਸੋਰੇਆਸਿਸ": "psoriasis",
        "ਗੈਸਟ੍ਰੋਐਂਟਰਾਈਟਿਸ": "gastroenteritis",
        "ਬਦਹਜ਼ਮੀ": "constipation",
        "ਨੀਂਦ ਨਾ ਆਉਣਾ": "insomnia",
        "ਮਾਈਗਰੇਨ": "migraine",
        "ਮੋਟਾਪਾ": "obesity",
        "ਥਾਇਰਾਇਡ": "thyroid disorder",
        "ਕੋਲੈਸਟ੍ਰੋਲ": "cholesterol",
        "ਹੱਡੀ ਕਮਜ਼ੋਰੀ": "osteoporosis",
        "ਦਿਮਾਗੀ ਦੌਰਾ": "stroke",
        "ਕੈਂਸਰ": "cancer",
        "ਟਿਊਬਰਕੁਲੋਸਿਸ": "tuberculosis",
        "ਹੈਪਾਟਾਈਟਿਸ": "hepatitis",
        "ਐਚਆਈਵੀ/ਏਡਸ": "HIV/AIDS",
        "ਮਲੇਰੀਆ": "malaria",
        "ਚਿਕਨ ਪੌਕਸ": "chickenpox",
        "ਖਸਰਾ": "measles",
        "ਡੈਂਗੂ": "dengue",
        "ਜ਼ੀਕਾ ਵਾਇਰਸ": "zika virus",
        "ਪੋਲਿਓ": "polio",
        "ਰੇਬੀਜ਼": "rabies",
        "ਟਾਇਫ਼ਾਇਡ": "typhoid",
        "ਕੋਲੇਰਾ": "cholera",
        "ਹਸਪਤਾਲ": "hospital",
        "ਡਾਕਟਰ": "doctor",
    },
    'ml': {
        "ജ്വരം": "fever",
        "തുമ്മല്‍": "cough",
        "തണുപ്പ്": "cold",
        "വൈശാഖം": "headache",
        "ശരീരത്തിലെ മധുമേഹം": "diabetes",
        "ഉയർന്ന രക്തച്ചാപ്പ്": "hypertension",
        "അസ്ത്മ": "asthma",
        "അലർജി": "allergy",
        "ഫ്ലു": "flu",
        "വയറുവേദന": "stomach ache",
        "വയറിളക്കം": "diarrhea",
        "ശരീരവേദനകൾ": "back pain",
        "ദുഖിത മനസ്സ്": "depression",
        "മനോബാധ": "anxiety",
        "സന്ധിവേദന": "arthritis",
        "ബ്രോങ്കൈറ്റിസ്": "bronchitis",
        "അനീമിയ": "anemia",
        "മൂത്ര മാർഗം പ്രതിരോധം": "urinary tract infection",
        "കാത് വൈറസ്": "ear infection",
        "സൈനുസൈറ്റിസ്": "sinusitis",
        "ത്വക്ക് കൊഴുപ്പ്": "skin rash",
        "എക്സിമ": "eczema",
        "സോരായാസിസ്": "psoriasis",
        "ഗെസ്ട്രോഎൻററൈറ്റിസ്": "gastroenteritis",
        "കബ്ജ്": "constipation",
        "അനിദ്ര": "insomnia",
        "മൈഗ്രെയ്ൻ": "migraine",
        "കഴുത്തല": "obesity",
        "തൈറോയിഡ്": "thyroid disorder",
        "കൊളസ്ട്രോള്": "cholesterol",
        " അസ്ഥിമാസിസ്": "osteoporosis",
        "സ്റ്റ്രോക്ക്": "stroke",
        "കാൻസർ": "cancer",
        "ക്ഷയം": "tuberculosis",
        "ഹെപ്പറ്റൈറ്റിസ്": "hepatitis",
        "എച്ച്.ഐ.വി/എഡ്സ്": "HIV/AIDS",
        "മലേറിയ": "malaria",
        "ചിക്കൻപോക്സ്": "chickenpox",
        "മീസൽസ്": "measles",
        "ഡെങ്ക്യു": "dengue",
        "ജീക്ക വൈറസ്": "zika virus",
        "പോളിയോ": "polio",
        "രേബീസ്": "rabies",
        "ടൈഫോയ്‌ഡ്": "typhoid",
        "കൊളറ": "cholera",
        "ആശ eli pital": "hospital",
        "ഡോക്ടര്": "doctor",
    },
    'ur': {
        "بخار": "fever",
        "ککھ": "cough",
        "نزلہ": "cold",
        "سر درد": "headache",
        "ذیابیطس": "diabetes",
        "بلڈ پریشر": "hypertension",
        "دمہ": "asthma",
        "الرژی": "allergy",
        "انفلوئنزا": "flu",
        "پیٹ درد": "stomach ache",
        "اسہال": "diarrhea",
        "پیٹھ درد": "back pain",
        "ڈپریشن": "depression",
        "انگزائٹی": "anxiety",
        "گٹھیا": "arthritis",
        "برونکائٹس": "bronchitis",
        "خون کی کمی": "anemia",
        "پیشاب کی نالی کا انفیکشن": "urinary tract infection",
        "کان کا انفیکشن": "ear infection",
        "سائنسائٹس": "sinusitis",
        "جلد کا خارش": "skin rash",
        "ایكزیما": "eczema",
        "سورایسِس": "psoriasis",
        "گیسٹروانٹرائٹس": "gastroenteritis",
        "قبض": "constipation",
        "نیند نہ آنا": "insomnia",
        "مایگرین": "migraine",
        "موٹاپا": "obesity",
        "تھائیرائیڈ کی خرابی": "thyroid disorder",
        "کولیسٹرول": "cholesterol",
        "ہڈیوں کی کمزوری": "osteoporosis",
        "فالج": "stroke",
        "کینسر": "cancer",
        "ٹی بی": "tuberculosis",
        "ہیپاٹائٹس": "hepatitis",
        "ایچ آئی وی/ایڈز": "HIV/AIDS",
        "ملیریا": "malaria",
        "چکن پاکس": "chickenpox",
        "خسرہ": "measles",
        "ڈینگی": "dengue",
        "زیكا وائرس": "zika virus",
        "پولیو": "polio",
        "ربیز": "rabies",
        "ٹائفائڈ": "typhoid",
        "کولیرہ": "cholera",
        "ہسپتال": "hospital",
        "ڈاکٹر": "doctor",
    },
    
}




translator = Translator()

def get_response(user_input, lang_code='en'):
    user_input = unicodedata.normalize('NFC', user_input.lower())
    response_key = "default"

    if lang_code in INPUT_KEYWORDS:
        keywords_map = INPUT_KEYWORDS[lang_code]
        for local_word, eng_key in keywords_map.items():
            if local_word in user_input:
                response_key = eng_key
                break
    else:
        for key in RESPONSES_EN:
            if key in user_input:
                response_key = key
                break

    reply = RESPONSES_EN.get(response_key, RESPONSES_EN["default"])

    # Translate reply if language is NOT English (including Hindi)
    if lang_code != 'en':
        try:
            translation = translator.translate(reply, dest=lang_code)
            return translation.text
        except Exception as e:
            print(f"Translation failed: {e}")
            return reply
    else:
        return reply
